TOKEN = "YOUR TOKEN"
PATH = "C:\\Users\\USER\\New folder\\"
ADMIN_ROLE = 1234
MODERATOR_ROLE = 12345
EVENT_CHANNEL_ID = 12345

METAMASK_PASSWORD = "PASSWORD"
METAMASK_WORD_1 ="WORD1"
METAMASK_WORD_2 ="WORD2"
METAMASK_WORD_3 ="WORD3"
METAMASK_WORD_4 ="WORD4"
METAMASK_WORD_5 ="WORD5"
METAMASK_WORD_6 ="WORD6"
METAMASK_WORD_7 ="WORD7"
METAMASK_WORD_8 ="WORD8"
METAMASK_WORD_9 ="WORD9"
METAMASK_WORD_10 ="WORD10"
METAMASK_WORD_11 ="WORD11"
METAMASK_WORD_12 ="WORD12"

EXTENSION_PATH = "./yourextension.crx"
CHROME_EXTENSION = "  "
